hyper_params:
  epochs: 100
  learning_rate: 0.01
  batch_size: 32
  num_workers: 4

data_params:
  img_crop_size: 85
  channels: 3
  classes: 1
  isic_mean: [0.8111, 0.5782, 0.4839] # [1.2721, 0.3341, -0.0479]
  isic_std: [0.1698, 0.1773, 0.2120] # [0.2508, 0.2654, 0.3213]
  isic_4000_mean: [0.6884, 0.5511, 0.5531]
  isic_4000_std: [0.3999, 0.3287, 0.3424]
  isic_resize_85_mean: [0.8457, 0.6837, 0.6727]
  isic_resize_85_std: [0.1409, 0.1405, 0.1739]

isic_paths:
  isic_data_path: ${hydra:runtime.cwd}/data/ISIC/data
  isic_metadata: ${hydra:runtime.cwd}/data/ISIC/metadata_combined.csv
  isic_root_dir: ${hydra:runtime.cwd}/data/ISIC
  data_col: isic_id

benign_malignant_experiment:
    label_col: benign_malignant
    metadata: ${hydra:runtime.cwd}/data/ISIC/benign_malignant.csv

family_history_experiment:
    label_col: family_hx_mm
    metadata: ${hydra:runtime.cwd}/data/ISIC/family_history.csv