defaults:
  - data: isic_base
  - hparams: isic_base
  - preprocessing: isic_base
  - task: family_history
  - plotting: plots
  - _self_

model:
  isic_base: ${hydra:runtime.cwd}/models/ # isic-base.pth
  isic_backdoor: ${hydra:runtime.cwd}/models/isic-backdoor.pth

backdoor:
  id: isic_base
  data: ${hydra:runtime.cwd}/data/processed/isic/isic-backdoor.npz
  reports: ${hydra:runtime.cwd}/reports/isic/backdoor
  load_model: True